apiVersion: v1
kind: Namespace
metadata:
  name: ping-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-api
  namespace: ping-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-api
  template:
    metadata:
      labels:
        app: ping-api
    spec:
      containers:
        - name: ping-api
          # Tiny server that returns "pong" on any path
          image: hashicorp/http-echo:0.2.3
          args:
            - "-text=pong"
          ports:
            - containerPort: 5678
          readinessProbe:
            httpGet:
              path: /
              port: 5678
            initialDelaySeconds: 1
            periodSeconds: 2
          livenessProbe:
            httpGet:
              path: /
              port: 5678
            initialDelaySeconds: 3
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ping-api
  namespace: ping-demo
spec:
  type: LoadBalancer
  selector:
    app: ping-api
  ports:
    - name: http
      port: 80          # cluster (and LB) port
      targetPort: 5678  # container port from the Deployment
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ping-ingress
  namespace: ping-demo
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ping-api
                port:
                  number: 80
